"""Add Phase 3 models: notifications, collaboration, agent conversations

Revision ID: 8f49708f8e03
Revises: 66f6beb5e0ab
Create Date: 2026-01-26 21:29:57.517485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f49708f8e03'
down_revision: Union[str, Sequence[str], None] = '66f6beb5e0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
